### ISSUE TITLE
Jigasi SIP gateway

### ISSUE THREAD

**Issue by wfleischer** [jitsi-contrib/meta#11]
Thanks for providing this organization to collaborate on jitsi extensions.

I would like to add https://github.com/wfleischer/jigate, which provides a self hosted SIP gateway for Jigasi based on FreeSWITCH.

**Comment by saghul** [comment]
That's awesome! Since you just created the repo how about I re-create it here, add you as a maintainer and you can push the changes?

**Comment by wfleischer** [comment]
That was fast! Thank you, @saghul. It is there: https://github.com/jitsi-contrib/jigate

**Comment by saghul** [comment]
❤️
