### ISSUE TITLE
Kubernetes Implementation

### ISSUE THREAD

**Issue by marner2** [jitsi-contrib/meta#2]
Could we have a repository for a Kubernetes deployment of the docker containers?

There are quite a few different ways to deploy jitsi with Kubernetes, not to mention different parameters as well depending on how you want it to scale. Just off the top of my head, there's
* Single-pod direct deployment currently in the docker-jitsi example directory (currently doesn't work with the latest docker images)
* Helm deployment
* Kustomize deployment
* Kompose transformation of the docker-compose.yml file maintained by Jitsi (results in multiple deployments and services)
* Dedicated deployments for various cloud k8s providers
* Deployments that automatically scale jitsi videobridge depending on demand

The decision would need to be made whether to make a dedicated repository for each one of those, or combine them all into a single "kubernetes" repository.

Also, an important consideration is that these should be working examples that have sensible defaults assuming simple kubernetes clusters (such as microk8s).

**Comment by saghul** [comment]
Sure thing! I'll add you to the org and you can start figuring things out. My gut feeling is that different repos are the way to go, at least until there is a "clear winner".

**Comment by saghul** [comment]
Added you.

**Comment by rsoika** [comment]
I just created the repo https://github.com/jitsi-contrib/kubernetes with a initial layout 

@marner2  if you like you can add your existing tutorial how to migrate a docker-compose stack into kubernetes using the kompose tool 

I also think that we can discuss additional topics like the configuration of services there.

**Comment by rsoika** [comment]
I just renamed the repo from 'kuberentes' to 'jitsi-kubernetes' avoiding name conflicts

https://github.com/jitsi-contrib/jitsi-kubernetes
