### ISSUE TITLE
prosody plugins related with JWT authentication

### ISSUE THREAD

**Issue by emrahcom** [jitsi-contrib/meta#3]
Hello,

I want to move the following Prosody modules into this repo

- [mod_token_affiliation](https://github.com/emrahcom/emrah-buster-templates/blob/master/machines/eb-jitsi/usr/share/jitsi-meet/prosody-plugins/mod_token_affiliation.lua)
- [mod_token_owner_party](https://github.com/emrahcom/emrah-buster-templates/blob/master/machines/eb-jitsi/usr/share/jitsi-meet/prosody-plugins/mod_token_owner_party.lua)

**Comment by saghul** [comment]
I just invited you to the org. Feel free to create some "prosody-plugins" project perhaps and move those there.
