### ISSUE TITLE
Jitsi Moodle plugin

### ISSUE THREAD

**Issue by marcoblancas** [jitsi-contrib/meta#5]
Not sure if projects to integrate Jitsi in other platforms are suitable for this.

We maintain https://moodle.org/plugins/mod_jitsi and as you can see it is installed in more than 6000 server over the world. Moodle is the most important LMS OpenSource used in Universities and Schools.

https://github.com/udima-university/moodle-mod_jitsi

**Comment by saghul** [comment]
Hey there! We'd be happy to host the repo in this organization if that's what you're asking :-)

It fits the criteria perfectly well: community maintained Jitsi projects.

**Comment by marcoblancas** [comment]
The project is hosted in our repo. I thought the idea was link to other projects related with Jitsi. Thank you, but we are not interested on moving our repo.

**Comment by saghul** [comment]
No worries. I started listing other Jitsi related projects here: https://jitsi.github.io/handbook/docs/community/third-party-software feel free to add the plugin to the list with a PR!
