### ISSUE TITLE
Operator :)

### ISSUE THREAD

**Issue by pierreozoux** [jitsi-contrib/meta#6]
Hey, we'd like a repo to commit our operator code for the hackathon and to the infinity \o/

thanks!

**Comment by aaronkvanmeerten** [comment]
How's this one:
https://github.com/jitsi-contrib/jitsi-kubernetes-operator

You've been sent an invite to join jitsi-contrib, and you should be able to commit there.  Please let us know if you run into problems

**Comment by pierreozoux** [comment]
Can you add 2 members?
https://github.com/hrenard
https://github.com/unteem

Danke :)

**Comment by pierreozoux** [comment]
Also, it seems I can't clone it, so I can't push to it? not sue I have enough rights to just start it.
If you make me owner of the repo, then I ca probably can do whatever I need without bothering.

**Comment by aaronkvanmeerten** [comment]
See if that resolves it for you, you can add the other members to this repo to see that you have that permission too.

**Comment by saghul** [comment]
@aaronkvanmeerten Please add them to the org with “member” role instead. That’s what I’ve done with other contributors and it gives them the ability to create repos.

**Comment by pierreozoux** [comment]
danke, all good!
