### ISSUE TITLE
Prosody plugin to fire HTTP POST calls on room/occupant events

### ISSUE THREAD

**Issue by shawnchin** [jitsi-contrib/meta#7]
Ref: https://community.jitsi.org/t/trace-user-activity-on-external-systems/102490/7?u=shawn

Would this be suitable/useful in jitsi-contrib?

**Comment by damencho** [comment]
Maybe just adding it in https://github.com/jitsi-contrib/prosody-plugins, wdyt?

**Comment by shawnchin** [comment]
Works for me. I'll put together a PR.

**Comment by damencho** [comment]
Thank you :)

**Comment by shawnchin** [comment]
By the way, I've only really tested this with JWT auth. 

It currently gets the occupant's name/email/id from `event.origin.jitsi_meet_context_user`. Would this be a problem when used with other forms of auth e.g. secure domain or ldap?

**Comment by damencho** [comment]
That is available only with jwt, for the rest you have only the occupant jid.

**Comment by shawnchin** [comment]
Thanks. 

I did a quick test using guest user and the module did not blow up which was my main concern 🙂
JSON payload sent as usual but without the name and email fields for occupant. Which matches expectation.

Will package it up and close this issue once PR is sent to jitis-contib/prosody-plugins.
