### ISSUE TITLE
directory for docker-swarm files

### ISSUE THREAD

**Issue by prayagsingh** [jitsi-contrib/meta#8]
Hello @saghul 
Can you please create a directory with the name `jitsi-docker-swarm` under `jitsi-contrib`?

**Comment by saghul** [comment]
👋  Hey there! Happy to do that. One quick question before going there though. I *think* that should kinda belong to the main repo since the idea is to work with the "standard Docker tooling". Are many changes necessary?

**Comment by prayagsingh** [comment]
I think you are right.
 ok, I'll push the files to `docker-jitsi-meet/examples/`.

**Comment by saghul** [comment]
Let's see how it looks like, maybe there is a better way to blend them. Closing this for now then.
