### ISSUE TITLE
Repo for podman

### ISSUE THREAD

**Issue by bcstinch** [jitsi-contrib/meta#9]
Hello, I have worked on hosting jitsi with podman both on my private blog https://tendie.haus/how-to-setup-a-basic-jitsi-instance-with-podman/ and via upstream issues. I would love to host a repo of examples in a more discoverable place.

**Comment by saghul** [comment]
Sounds good! I'll create a pod an repo here and add you to the org.

**Comment by bcstinch** [comment]
Sounds good, thanks!

**Comment by saghul** [comment]
Just sent you an invite and created https://github.com/jitsi-contrib/jitsi-podman cheers!
